import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as path from "path";
import { check, type Decision } from "./cmdguard-pure";

// ⚠ THE TWO PARSERS AGREE, NOT ONLY THE TWO TABLES (B18.50).
//
// testdata/cmdguard-parser-corpus.json is generated by agent/internal/cmdguard/parser_parity_test.go
// from the shared tables crossed with the shapes a hand port gets wrong — separators, quoting,
// escapes, redirection, substitution, empty segments, whitespace, unicode, embedded newlines — and
// records the Go parser's verdict for each command. This asserts the port returns the same decision
// AND reason for every one. The Go side asserts its own verdicts against the same file, so a change
// to either parser that alters a verdict fails a build.
//
// The dangerous direction is the port allowing what Go does not: the extension would then run
// unattended a command the CLI stops to ask about. Failures are grouped by direction so that one
// reads first.

interface Case {
  command: string;
  decision: Decision;
  reason: string;
}

function parserCorpusPath(): string {
  let dir = __dirname;
  for (let i = 0; i < 10; i++) {
    const candidate = path.join(dir, "testdata", "cmdguard-parser-corpus.json");
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // ⚠ LOUD, NOT EMPTY. A corpus that has moved would otherwise assert nothing and pass.
  throw new Error(
    `cmdguard parser corpus not found above ${__dirname} — this suite would have verified nothing`,
  );
}

const corpus = JSON.parse(fs.readFileSync(parserCorpusPath(), "utf8")) as { cases: Case[] };

// A literal, not a number read from the file: a floor read from the corpus could be emptied with it.
const FLOOR = 2000;

test("the parser corpus is loaded and exercises every decision", () => {
  assert.ok(corpus.cases.length >= FLOOR, `only ${corpus.cases.length} cases — too thin to say the parsers agree`);
  for (const d of ["allow", "confirm", "refuse"] as const) {
    const n = corpus.cases.filter((c) => c.decision === d).length;
    assert.ok(n >= 100, `only ${n} ${d} verdicts — the corpus does not exercise that decision`);
  }
});

test("the TypeScript parser returns the Go parser's verdict for every command in the corpus", () => {
  const rank: Record<Decision, number> = { allow: 0, confirm: 1, refuse: 2 };
  const wider: string[] = [];
  const narrower: string[] = [];
  const reworded: string[] = [];
  for (const c of corpus.cases) {
    const v = check(c.command);
    const line = `check(${JSON.stringify(c.command)}) = ${v.decision} ${JSON.stringify(v.reason)}, Go says ${c.decision} ${JSON.stringify(c.reason)}`;
    if (rank[v.decision] < rank[c.decision]) wider.push(line);
    else if (rank[v.decision] > rank[c.decision]) narrower.push(line);
    else if (v.reason !== c.reason) reworded.push(line);
  }
  const report = [
    ["the port is MORE permissive than Go", wider],
    ["the port is stricter than Go", narrower],
    ["same decision, different reason", reworded],
  ]
    .filter(([, l]) => l.length > 0)
    .map(([what, l]) => `${what} (${l.length}):\n  ${(l as string[]).slice(0, 20).join("\n  ")}`)
    .join("\n");
  assert.equal(
    wider.length + narrower.length + reworded.length,
    0,
    `the two cmdguard parsers disagree on ${corpus.cases.length} generated commands:\n${report}`,
  );
});
